# Generated by Django 5.2.4 on 2025-07-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='UAE', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_images')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('top_attractions', models.TextField(blank=True, null=True)),
                ('travel_type', models.CharField(choices=[('adventure', 'Adventure'), ('family', 'Family'), ('romantic', 'Romantic'), ('cultural', 'Cultural'), ('relaxation', 'Relaxation'), ('beach', 'Beach'), ('hill_station', 'Hill Station')], max_length=50)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
