# Generated by Django 5.2.4 on 2025-08-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_tripmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('activities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destinationmodel')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.tripmodel')),
            ],
        ),
    ]
